name: Code Quality

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  all-in-one:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Run Typecheck
        run: yarn typecheck

      - name: Run Lint
        run: yarn lint:ci

      - name: Merge Linting Results
        run: node ./ci/merge-eslint-reports.js

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v2
        with:
          report-json: "merged_eslint_report.json"

      - name: Run Tests
        run: yarn test
